services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $allowedLocales: '%markocupic_contao_translation.allowed_locales%'
            $contaoCsrfTokenName: '%contao.csrf_token_name%'

    Markocupic\ContaoTranslationBundle\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}

    # Do not handle this class as a service
    Markocupic\ContaoTranslationBundle\Export\XliffWriter:
        autoconfigure: false
        autowire: false

    # Do not handle this class as a service
    Markocupic\ContaoTranslationBundle\Import\ParseXml:
        autoconfigure: false
        autowire: false

    # Add a session bag
    Markocupic\ContaoTranslationBundle\Session\Attribute\ArrayAttributeBag:
        arguments:
            - _markocupic_contao_translation_attributes
        calls:
            - [ setName, [ markocupic_contao_translation ] ]
